// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PartnersIndexImport } from './routes/partners/index'
import { Route as PackagesAndLabelsIndexImport } from './routes/packages-and-labels/index'
import { Route as PackagesAndLabelsCreateImport } from './routes/packages-and-labels/create'
import { Route as PackagesAndLabelsIdImport } from './routes/packages-and-labels/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PartnersIndexRoute = PartnersIndexImport.update({
  path: '/partners/',
  getParentRoute: () => rootRoute,
} as any)

const PackagesAndLabelsIndexRoute = PackagesAndLabelsIndexImport.update({
  path: '/packages-and-labels/',
  getParentRoute: () => rootRoute,
} as any)

const PackagesAndLabelsCreateRoute = PackagesAndLabelsCreateImport.update({
  path: '/packages-and-labels/create',
  getParentRoute: () => rootRoute,
} as any)

const PackagesAndLabelsIdRoute = PackagesAndLabelsIdImport.update({
  path: '/packages-and-labels/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/packages-and-labels/$id': {
      preLoaderRoute: typeof PackagesAndLabelsIdImport
      parentRoute: typeof rootRoute
    }
    '/packages-and-labels/create': {
      preLoaderRoute: typeof PackagesAndLabelsCreateImport
      parentRoute: typeof rootRoute
    }
    '/packages-and-labels/': {
      preLoaderRoute: typeof PackagesAndLabelsIndexImport
      parentRoute: typeof rootRoute
    }
    '/partners/': {
      preLoaderRoute: typeof PartnersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  PackagesAndLabelsIdRoute,
  PackagesAndLabelsCreateRoute,
  PackagesAndLabelsIndexRoute,
  PartnersIndexRoute,
])
